### PR TITLE
feat: easy startup for dev environment setup and code debug

### PR DESCRIPTION
**Pull request by icezohu**

### CODE REVIEW

**Comment by mzxyz** [comment]
Please clean you git history, looks it was branch from your previous branch other than main

**Comment by icezohu** [comment]
> Please clean you git history, looks it was branch from your previous branch other than main

Hi @mzxyz , I merged main branch several times to verify my change, now I have rebased my branch from latest main branch commit. Please review again. Thank you very much.

**Comment by mzxyz** [comment]
Awesome work, please also update the `README` for running locally, otherwise LGTM

**Review by mzxyz — APPROVED** [review]

**Comment by icezohu** [comment]
`README` updated ^^

**Pull request merged**
